# Generated by Django 3.2.6 on 2023-06-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20230611_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie',
            new_name='title',
        ),
    ]
