# Generated by Django 3.2.6 on 2023-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_alter_movie_imdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
