# Generated by Django 3.2.6 on 2023-06-12 13:52

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_auto_20230612_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=register.models.NumericAutoField(unique=True),
        ),
    ]
