# Generated by Django 3.2.6 on 2023-06-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20230612_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('movie', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('text', models.TextField()),
            ],
        ),
    ]
