# Generated by Django 3.2.6 on 2023-06-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
