# Generated by Django 3.2.6 on 2023-06-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0020_delete_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
