# Generated by Django 3.2.6 on 2023-10-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_remove_review_imdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
