# Generated by Django 3.2.6 on 2023-10-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0025_movie_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_path',
        ),
    ]
